export const browserCoreExamples = [
  "godseye browser status",
  "godseye browser start",
  "godseye browser stop",
  "godseye browser tabs",
  "godseye browser open https://example.com",
  "godseye browser focus abcd1234",
  "godseye browser close abcd1234",
  "godseye browser screenshot",
  "godseye browser screenshot --full-page",
  "godseye browser screenshot --ref 12",
  "godseye browser snapshot",
  "godseye browser snapshot --format aria --limit 200",
  "godseye browser snapshot --efficient",
  "godseye browser snapshot --labels",
];

export const browserActionExamples = [
  "godseye browser navigate https://example.com",
  "godseye browser resize 1280 720",
  "godseye browser click 12 --double",
  'godseye browser type 23 "hello" --submit',
  "godseye browser press Enter",
  "godseye browser hover 44",
  "godseye browser drag 10 11",
  "godseye browser select 9 OptionA OptionB",
  "godseye browser upload /tmp/godseye/uploads/file.pdf",
  'godseye browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "godseye browser dialog --accept",
  'godseye browser wait --text "Done"',
  "godseye browser evaluate --fn '(el) => el.textContent' --ref 7",
  "godseye browser console --level error",
  "godseye browser pdf",
];
